name: 'Setup o3de-extras'
description: 'Custom action to setup o3de-extras'
author: 'Robotec.AI'

inputs:
  script-path:
    description: 'Path to the script with all tests defined by the user'
    required: true
    default: 'test/test-script.sh'
  container:
    description: 'Container to use for the tests'
    required: false
    default: 'khasreto/o3de-extras-daily_dev'

runs:
  using: 'node16'
  main: 'dist/index.js'
