name: Docker Build and Publish 2305-2305

on:
  schedule:
    - cron: '0 3 * * *' # Runs every day at 3 am
  workflow_dispatch: # Run manually

jobs:
  build-and-publish:
    runs-on: self-hosted
    # Only run on main branch
    if: github.ref == 'refs/heads/main' 
    steps:
    - uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        file: ./docker/o3de-2305-extras-2305/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/o3de-2305-extras-2305:latest